name: Generate Snake Contribution
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 20 * * *" # Runs every day at 8 PM UTC

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: mandalfy # Replace with your GitHub username
          output: dist/snake.svg

      - name: Commit and push snake.svg
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          mkdir -p output
          mv dist/snake.svg output/snake.svg
          git add output/snake.svg
          git commit -m "Generate snake.svg for contributions grid"
          git push origin main
